Repository Yandall/pricepro-web, pull requests merged in 2023-06, with the labels that each got.

#24 Patch v0.1.2-beta
  changelog.md
  components/Footer.tsx
  components/MainLayout.tsx
  components/NavBar/NavBar.tsx
  components/NavBar/NavList.tsx
  pages/product/[id].tsx
  pages/search.tsx
Labels: bug, New feature, refactor

#25 Patch v0.1.3-beta
  changelog.md
  components/Footer.tsx
  components/NavBar/NavBar.tsx
  components/ProductCard.tsx
  pages/_app.tsx
  pages/api/sitemap.ts
  pages/index.tsx
  pages/product/[id].tsx
  pages/search.tsx
  pages/suggest.tsx
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/robots.txt
  public/site.webmanifest
Labels: documentation, refactor

#26 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#28 Patch v0.1.4-beta
  .gitignore
  changelog.md
  package-lock.json
  package.json
  pages/index.tsx
  pages/product/[id].tsx
Labels: refactor
